// sites/cv.arolariu.ro/src/presentation/human/Hero.svelte
<script lang="ts">
  import {author} from "@/data";

  let heroVisible = $state(false);
  let imageLoaded = $state(false);

  // Trigger hero animation shortly after mount
  $effect(() => {
    const t = setTimeout(() => (heroVisible = true), 200);
    return () => clearTimeout(t);
  });

  function handleImageLoad() {
    imageLoaded = true;
  }
</script>

<section
  class="pt-24 pb-16 px-6 relative overflow-hidden"
  style="view-transition-name: hero-section;">
  <!-- Theme-aware animated gradient background elements -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <div
      class="absolute top-20 left-10 w-72 h-72 rounded-full blur-3xl animate-float transition-all duration-500 bg-gradient-to-tr from-blue-500/10 via-purple-500/8 to-pink-500/5 dark:from-blue-500/15 dark:via-purple-500/10 dark:to-pink-500/5">
    </div>
    <div
      class="absolute bottom-20 right-10 w-96 h-96 rounded-full blur-3xl animate-float-delayed transition-all duration-500 bg-gradient-to-tr from-pink-500/10 via-purple-500/8 to-blue-500/5 dark:from-pink-500/15 dark:via-purple-500/10 dark:to-blue-500/5">
    </div>
  </div>

  <div class="container mx-auto text-center relative z-10">
    <!-- Profile Image with enhanced animation -->
    <div class="mb-8 relative inline-block">
      <div
        class="absolute inset-0 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500 blur-md opacity-50 scale-105 transition-opacity duration-500"
        class:opacity-0={!imageLoaded}>
      </div>
      <img
        src="/author.jpeg"
        alt={author.name}
        onload={handleImageLoad}
        class="w-48 h-48 rounded-full mx-auto border-4 border-blue-500 dark:border-blue-400 shadow-xl relative transition-all duration-700 ease-out"
        class:opacity-100={heroVisible && imageLoaded}
        class:opacity-0={!heroVisible || !imageLoaded}
        class:scale-100={heroVisible}
        class:scale-90={!heroVisible}
        style="view-transition-name: profile-image;" />
    </div>

    <!-- Name with staggered letter reveal feel -->
    <div
      class="transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 100ms;">
      <h1 class="text-4xl md:text-6xl font-bold mb-4">
        <span class="inline-block">Alexandru-Razvan</span>
        <span class="text-blue-600 dark:text-blue-400 inline-block"> Olariu </span>
      </h1>
    </div>

    <!-- Tagline with animated underline effect -->
    <div
      class="transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 250ms;">
      <p class="text-xl md:text-2xl text-gray-600 dark:text-gray-300 mb-6 relative inline-block">
        <span class="relative">
          Software Engineer
          <span
            class="absolute bottom-0 left-0 w-full h-0.5 bg-blue-500/30 dark:bg-blue-400/30 transform origin-left transition-transform duration-700 delay-700"
            class:scale-x-100={heroVisible}
            class:scale-x-0={!heroVisible}></span>
        </span>
        <span class="text-gray-400 dark:text-gray-500 mx-2">|</span>
        <span class="relative">
          Solution Architect
          <span
            class="absolute bottom-0 left-0 w-full h-0.5 bg-purple-500/30 dark:bg-purple-400/30 transform origin-left transition-transform duration-700 delay-800"
            class:scale-x-100={heroVisible}
            class:scale-x-0={!heroVisible}></span>
        </span>
        <span class="text-gray-400 dark:text-gray-500 mx-2">|</span>
        <span class="relative">
          Mentor
          <span
            class="absolute bottom-0 left-0 w-full h-0.5 bg-pink-500/30 dark:bg-pink-400/30 transform origin-left transition-transform duration-700 delay-900"
            class:scale-x-100={heroVisible}
            class:scale-x-0={!heroVisible}></span>
        </span>
      </p>
    </div>

    <!-- Description -->
    <div
      class="transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 400ms;">
      <p class="text-lg text-gray-500 dark:text-gray-400 mb-8 max-w-2xl mx-auto leading-relaxed">
        {new Date().getFullYear() - 2000}-year-old passionate software engineer based in {author.location}, dedicated to creating innovative
        solutions and building exceptional digital experiences.
      </p>
    </div>

    <!-- CTA Buttons -->
    <div
      class="flex flex-col sm:flex-row gap-4 justify-center transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 550ms;">
      <a
        href="#contact"
        class="group bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 text-white px-8 py-3 rounded-xl font-semibold transition-all duration-300 hover:shadow-lg hover:shadow-blue-500/25 dark:hover:shadow-blue-400/25 hover:-translate-y-0.5 active:translate-y-0">
        <span class="flex items-center justify-center gap-2">
          Get In Touch
          <svg
            class="w-4 h-4 transition-transform group-hover:translate-x-1"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M17 8l4 4m0 0l-4 4m4-4H3" />
          </svg>
        </span>
      </a>
      <a
        href="#experience"
        class="group border-2 border-blue-500 text-blue-600 dark:text-blue-400 hover:bg-blue-500 hover:text-white dark:hover:bg-blue-400 dark:hover:text-gray-900 px-8 py-3 rounded-xl font-semibold transition-all duration-300 hover:-translate-y-0.5 active:translate-y-0">
        <span class="flex items-center justify-center gap-2">
          View My Work
          <svg
            class="w-4 h-4 transition-transform group-hover:translate-y-0.5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M19 14l-7 7m0 0l-7-7m7 7V3" />
          </svg>
        </span>
      </a>
    </div>
  </div>
</section>

<style>
  @keyframes float {
    0%,
    100% {
      transform: translateY(0) scale(1);
    }
    50% {
      transform: translateY(-20px) scale(1.05);
    }
  }

  .animate-float {
    animation: float 8s ease-in-out infinite;
  }

  .animate-float-delayed {
    animation: float 8s ease-in-out infinite;
    animation-delay: -4s;
  }

  @media (prefers-reduced-motion: reduce) {
    .animate-float,
    .animate-float-delayed {
      animation: none;
    }
  }
</style>

// sites/arolariu.ro/src/app/_components/Hero.tsx
/** @format */

import {motion} from "motion/react";
import {useTranslations} from "next-intl";
import Link from "next/link";
import TechSphere from "../_effects/TechSphere";

/**
 * The hero section of the homepage, CSR'ed.
 * This component renders the hero section of the homepage.
 * It displays a title, subtitle, and a call-to-action button.
 * The hero section is animated using the `motion` library.
 * @returns The hero section of the homepage, CSR'ed.
 */
export default function HeroSection(): React.JSX.Element {
  const t = useTranslations("Home");
  return (
    <section className='relative min-h-screen overflow-hidden py-20'>
      <article className='mx-auto grid grid-cols-1 items-center gap-12 px-4 lg:grid-cols-2'>
        {/* Left side */}
        <motion.div
          initial={{opacity: 0, scale: 0.8}}
          animate={{opacity: 1, scale: 1}}
          transition={{duration: 0.8, delay: 0.3}}
          className='relative z-10'>
          <h1 className='mt-6 text-4xl font-normal text-white 2xsm:text-center sm:mt-10 sm:text-5xl md:text-left lg:text-6xl xl:text-8xl'>
            <span className='bg-gradient-to-r from-cyan-500 to-purple-500 bg-clip-text text-transparent'>{t("title")}</span>
          </h1>
          <p className='mt-4 max-w-lg text-xl text-gray-500 2xsm:text-center md:text-left lg:max-w-2xl'>
            {t.rich("subtitle", {
              br: (chunks) => (
                <>
                  <br />
                  {chunks}
                </>
              ),
            })}
          </p>
          <div className='relative mt-8 inline-flex 2xsm:ml-[26%] md:ml-0'>
            <div className='absolute -inset-px rounded-full bg-gradient-to-r from-cyan-500 to-purple-500 transition-all duration-200 group-hover:shadow-lg group-hover:shadow-cyan-500/50' />
            <Link
              href='/domains'
              title=''
              className='relative inline-flex rounded-full border border-transparent bg-black px-8 py-3 text-white'>
              {t("cta")}
            </Link>
          </div>

          <div>
            <div className='mt-8 inline-flex items-center border-t border-gray-800 pt-6 dark:border-gray-300'>
              <svg
                className='h-6 w-6'
                viewBox='0 0 24 24'
                fill='none'
                strokeWidth='1.5'
                xmlns='http://www.w3.org/2000/svg'>
                <path
                  d='M13 7.00003H21M21 7.00003V15M21 7.00003L13 15L9 11L3 17'
                  stroke='url(#a)'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                />
              </svg>

              <span className='2xsm:text-center md:text-left'>{t("appreciation")}</span>
            </div>
          </div>
        </motion.div>
        {/* Right side */}
        <motion.div
          initial={{opacity: 0, scale: 0.8}}
          animate={{opacity: 1, scale: 1}}
          transition={{duration: 0.8, delay: 0.3}}
          className='relative flex flex-col items-center justify-center'>
          <div className='relative mx-auto w-full max-w-[400px]'>
            <motion.div
              className='absolute -left-20 -top-20 h-40 w-40 rounded-full bg-primary/20 blur-3xl'
              animate={{
                scale: [1, 1.2, 1],
                opacity: [0.3, 0.5, 0.3],
              }}
              transition={{
                duration: 8,
                repeat: Number.POSITIVE_INFINITY,
                repeatType: "reverse",
              }}
            />
            <motion.div
              className='absolute -bottom-20 -right-20 h-40 w-40 rounded-full bg-purple-500/20 blur-3xl'
              animate={{
                scale: [1, 1.2, 1],
                opacity: [0.3, 0.5, 0.3],
              }}
              transition={{
                duration: 6,
                repeat: Number.POSITIVE_INFINITY,
                repeatType: "reverse",
              }}
            />

            <div className='hidden lg:block'>
              <TechSphere />
            </div>

            {/* Mobile-only animation */}
            <div className='block w-full sm:hidden'>
              <div className='relative flex h-60 w-full items-center justify-center'>
                <motion.div
                  className='absolute h-32 w-32 rounded-full bg-primary/20 blur-xl'
                  animate={{
                    scale: [1, 1.2, 1],
                    opacity: [0.3, 0.5, 0.3],
                  }}
                  transition={{
                    duration: 4,
                    repeat: Number.POSITIVE_INFINITY,
                    repeatType: "reverse",
                  }}
                />
              </div>
            </div>
          </div>
        </motion.div>
      </article>
    </section>
  );
}
