// sites/cv.arolariu.ro/src/presentation/Badge.svelte
<script lang="ts">
  /**
   * Badge component for skill tokens, statuses, tags.
   *
   * Props:
   *  - text: displayed label
   *  - color: semantic accent key
   *  - variant: visual style
   *  - size: scale (sm | md)
   *  - title?: optional title / tooltip
   */
  type Color = "blue" | "green" | "purple" | "pink" | "orange" | "gray";
  type Variant = "solid" | "soft" | "outline";
  type Size = "sm" | "md";

  interface Props {
    text: string;
    color?: Color;
    variant?: Variant;
    size?: Size;
    title?: string;
    class?: string;
    style?: string;
  }

  let {text, color = "blue", variant = "soft", size = "md", title = "", style = "", class: extraClass = ""}: Props = $props();

  const base =
    "inline-flex items-center font-medium rounded-full select-none transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 ring-offset-transparent ring-blue-500/50";

  const sizeMap: Record<Size, string> = {
    sm: "text-xs px-2 py-0.5",
    md: "text-sm px-3 py-1",
  };

  const palettes: Record<Color, {solid: string; soft: string; outline: string}> = {
    blue: {
      solid: "bg-blue-600 text-white hover:bg-blue-500",
      soft: "bg-blue-500/10 text-blue-600 dark:text-blue-400 ring-1 ring-inset ring-blue-500/20",
      outline: "text-blue-600 dark:text-blue-400 border border-blue-500/40 hover:bg-blue-500/10",
    },
    green: {
      solid: "bg-green-600 text-white hover:bg-green-500",
      soft: "bg-green-500/10 text-green-600 dark:text-green-400 ring-1 ring-inset ring-green-500/20",
      outline: "text-green-600 dark:text-green-400 border border-green-500/40 hover:bg-green-500/10",
    },
    purple: {
      solid: "bg-purple-600 text-white hover:bg-purple-500",
      soft: "bg-purple-500/10 text-purple-600 dark:text-purple-400 ring-1 ring-inset ring-purple-500/20",
      outline: "text-purple-600 dark:text-purple-400 border border-purple-500/40 hover:bg-purple-500/10",
    },
    pink: {
      solid: "bg-pink-600 text-white hover:bg-pink-500",
      soft: "bg-pink-500/10 text-pink-600 dark:text-pink-400 ring-1 ring-inset ring-pink-500/20",
      outline: "text-pink-600 dark:text-pink-400 border border-pink-500/40 hover:bg-pink-500/10",
    },
    orange: {
      solid: "bg-orange-500 text-white hover:bg-orange-400",
      soft: "bg-orange-500/10 text-orange-600 dark:text-orange-400 ring-1 ring-inset ring-orange-500/20",
      outline: "text-orange-600 dark:text-orange-400 border border-orange-500/40 hover:bg-orange-500/10",
    },
    gray: {
      solid: "bg-gray-700 text-white hover:bg-gray-600",
      soft: "bg-gray-500/10 text-gray-700 dark:text-gray-300 ring-1 ring-inset ring-gray-500/20",
      outline: "text-gray-700 dark:text-gray-300 border border-gray-400/40 dark:border-gray-600 hover:bg-gray-500/10",
    },
  };

  const classes = `${base} ${sizeMap[size]} ${palettes[color][variant]} ${extraClass}`;
</script>

<span
  class={classes}
  {title}
  aria-label={title || text}
  {style}>{text}</span>

// packages/components/src/components/ui/badge.tsx
"use client";

import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "./../../lib/utils";

const badgeVariants = cva(
  "inline-flex items-center justify-center rounded-md border border-neutral-200 px-2 py-0.5 text-xs font-medium w-fit whitespace-nowrap shrink-0 [&>svg]:size-3 gap-1 [&>svg]:pointer-events-none focus-visible:border-neutral-950 focus-visible:ring-neutral-950/50 focus-visible:ring-[3px] aria-invalid:ring-red-500/20 dark:aria-invalid:ring-red-500/40 aria-invalid:border-red-500 transition-[color,box-shadow] overflow-hidden dark:border-neutral-800 dark:focus-visible:border-neutral-300 dark:focus-visible:ring-neutral-300/50 dark:aria-invalid:ring-red-900/20 dark:dark:aria-invalid:ring-red-900/40 dark:aria-invalid:border-red-900",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-neutral-900 text-neutral-50 [a&]:hover:bg-neutral-900/90 dark:bg-neutral-50 dark:text-neutral-900 dark:[a&]:hover:bg-neutral-50/90",
        secondary:
          "border-transparent bg-neutral-100 text-neutral-900 [a&]:hover:bg-neutral-100/90 dark:bg-neutral-800 dark:text-neutral-50 dark:[a&]:hover:bg-neutral-800/90",
        destructive:
          "border-transparent bg-red-500 text-white [a&]:hover:bg-red-500/90 focus-visible:ring-red-500/20 dark:focus-visible:ring-red-500/40 dark:bg-red-900 dark:[a&]:hover:bg-red-900/90 dark:focus-visible:ring-red-900/20 dark:dark:focus-visible:ring-red-900/40",
        outline:
          "text-neutral-950 [a&]:hover:bg-neutral-100 [a&]:hover:text-neutral-900 dark:text-neutral-50 dark:[a&]:hover:bg-neutral-800 dark:[a&]:hover:text-neutral-50",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

function Badge({
  className,
  variant,
  asChild = false,
  ...props
}: React.ComponentProps<"span"> &
  VariantProps<typeof badgeVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot : "span";

  return (
    <Comp
      data-slot="badge"
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  );
}

export { Badge, badgeVariants };
