// sites/cv.arolariu.ro/src/presentation/human/Experience.svelte
<!-- @format -->
<script lang="ts">
  import {AnimatedSection} from "@/components/motion";
  import {experiencesAsArray, parseList} from "@/data/experiences";
  import Badge from "@/presentation/Badge.svelte";
</script>

<section
  id="experience"
  class="py-16 px-6 relative overflow-hidden">
  <!-- Theme-aware gradient background -->
  <div
    class="absolute inset-0 transition-all duration-500 bg-gradient-to-br from-blue-500/5 via-purple-500/4 to-pink-500/3 dark:from-blue-500/8 dark:via-purple-500/6 dark:to-pink-500/4"
  ></div>

  <div class="container mx-auto relative z-10">
    <AnimatedSection
      id="experience-title"
      animation="fade-up">
      <div class="mb-12 text-center">
        <h2
          id="experience-heading"
          class="font-bold text-3xl">
          Professional <span class="text-blue-600 dark:text-blue-400">Experience</span>
        </h2>
      </div>
    </AnimatedSection>

    <div class="max-w-6xl mx-auto">
      <div class="space-y-8">
        {#each experiencesAsArray as experience, index}
          <AnimatedSection
            id="experience-{index}"
            animation="fade-up"
            delay={index * 200}>
            <div
              class="backdrop-blur-sm rounded-xl p-8 shadow-lg hover-lift border border-gray-200 dark:border-gray-700 transition-all duration-300 bg-white/80 dark:bg-black/40">
              <div class="flex flex-col lg:flex-row lg:items-start lg:justify-between mb-6">
                <div class="flex-1">
                  <h3 class="text-2xl font-semibold text-blue-600 dark:text-blue-400 mb-2">
                    {experience.title}
                  </h3>
                  <p class="text-xl text-gray-800 dark:text-gray-200 mb-2">{experience.company}</p>
                  <p class="text-gray-600 dark:text-gray-400 mb-4">{experience.location}</p>
                  <p class="text-gray-700 dark:text-gray-300 leading-relaxed">
                    {experience.description}
                  </p>
                </div>
                <div class="lg:ml-8 mt-4 lg:mt-0 block 2xsm:hidden">
                  <div
                    class="bg-gradient-to-r from-blue-500 to-purple-500 text-white px-4 py-2 rounded-full text-sm font-semibold whitespace-nowrap">
                    {experience.period}
                  </div>
                </div>
              </div>

              {#if experience.responsibilities && experience.responsibilities.trim()}
                <div class="mb-6">
                  <h4 class="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-3"> Key Responsibilities </h4>
                  <ul class="space-y-2 stagger-animation">
                    {#each parseList(experience.responsibilities) as item, i}
                      <li
                        class="flex items-start"
                        style={`--delay:${index * 200 + i * 90}ms`}>
                        <span class="mr-3 mt-1 text-sm font-medium text-blue-500 dark:text-blue-400">▶</span>
                        <span
                          class="text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors duration-200"
                          >{item}</span>
                      </li>
                    {/each}
                  </ul>
                </div>
              {/if}

              {#if experience.achievements && experience.achievements.trim()}
                <div class="mb-6">
                  <h4 class="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-3"> Key Achievements </h4>
                  <ul class="space-y-2 stagger-animation">
                    {#each parseList(experience.achievements) as item, i}
                      <li
                        class="flex items-start"
                        style={`--delay:${index * 200 + 100 + i * 90}ms`}>
                        <span class="mr-3 mt-1 text-sm font-medium text-green-500 dark:text-green-400">✓</span>
                        <span
                          class="text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors duration-200"
                          >{item}</span>
                      </li>
                    {/each}
                  </ul>
                </div>
              {/if}

              <div>
                <h4 class="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-3"> Technologies & Skills </h4>
                <div class="flex flex-wrap gap-2">
                  {#each parseList(experience.techAndSkills) as skill, skillIndex}
                    <Badge
                      text={skill}
                      color="blue"
                      size="sm"
                      variant="outline"
                      class="stagger-animation"
                      style={`--delay:${index * 200 + skillIndex * 50}ms`} />
                  {/each}
                </div>
              </div>
            </div>
          </AnimatedSection>
        {/each}
      </div>
    </div>
  </div>
</section>

// sites/arolariu.ro/src/app/about/the-author/_components/Experience.tsx
/** @format */

"use client";

import {Badge} from "@arolariu/components";
import {AnimatePresence, motion} from "motion/react";
import {useTranslations} from "next-intl";
import React, {useState} from "react";
import {CgMicrosoft} from "react-icons/cg";
import {SiIntel, SiUbisoft} from "react-icons/si";
import {TbBriefcase, TbCalendar, TbChevronRight, TbMap} from "react-icons/tb";

type ExperienceType = {
  company: string;
  role: string;
  period: string;
  location: string;
  description: string;
  responsibilities: string[];
  achievements: string[];
  skills: string[];
  logo: React.JSX.Element;
};

const WorkCard = (props: Readonly<{experience: ExperienceType}>) => {
  const {experience} = props;

  return (
    <motion.div
      initial={{opacity: 0, x: 20}}
      animate={{opacity: 1, x: 0}}
      exit={{opacity: 0, x: -20}}
      transition={{duration: 0.3}}
      className='relative left-0 top-0 h-full w-full overflow-hidden rounded-xl border border-border/50 bg-card p-6 shadow-lg'>
      <div className='absolute left-0 top-0 h-1 w-full bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500' />

      <div className='mb-6 flex items-start justify-between'>
        <div>
          <h3 className='text-glow text-2xl font-bold'>{experience.role}</h3>
          <div className='mt-1 flex items-center text-muted-foreground'>
            <span className='font-medium'>{experience.company}</span>
          </div>
          <div className='mt-1 flex items-center text-sm text-muted-foreground'>
            <TbMap className='mr-1 h-3 w-3' />
            <span>{experience.location}</span>
          </div>
        </div>

        <div className='flex h-16 w-16 items-center justify-center rounded-lg bg-background'>
          <motion.div className='flex h-10 w-10 items-center justify-center rounded-full bg-background text-muted-foreground transition-colors duration-300'>
            {experience.logo}
          </motion.div>
        </div>
      </div>

      <p className='mb-6 text-muted-foreground'>{experience.description}</p>

      <div className='mb-6'>
        <h4 className='mb-3 text-lg font-semibold'>Responsibilites</h4>
        <ul className='space-y-2'>
          {experience.responsibilities.map((responsability, i) => (
            <motion.li
              key={`${responsability.slice(0, 20)}`}
              className='flex items-start'
              initial={{opacity: 0, x: -10}}
              animate={{opacity: 1, x: 0}}
              transition={{delay: i * 0.1, duration: 0.3}}>
              <TbChevronRight className='mr-2 mt-1 h-4 w-4 flex-shrink-0 text-primary' />
              <span>{responsability}</span>
            </motion.li>
          ))}
        </ul>
      </div>

      <div className='mb-6'>
        <h4 className='mb-3 text-lg font-semibold'>Achievements</h4>
        <ul className='space-y-2'>
          {experience.achievements.map((achievement, i) => (
            <motion.li
              key={`${achievement.slice(0, 20)}`}
              className='flex items-start'
              initial={{opacity: 0, x: -10}}
              animate={{opacity: 1, x: 0}}
              transition={{delay: i * 0.1, duration: 0.3}}>
              <TbChevronRight className='mr-2 mt-1 h-4 w-4 flex-shrink-0 text-primary' />
              <span>{achievement}</span>
            </motion.li>
          ))}
        </ul>
      </div>

      <div>
        <h4 className='mb-3 text-lg font-semibold'>Technologies & Skills</h4>
        <div className='flex flex-wrap gap-2'>
          {experience.skills.map((skill, i) => (
            <motion.div
              key={`${skill.slice(0, 20)}`}
              initial={{opacity: 0, scale: 0.8}}
              animate={{opacity: 1, scale: 1}}
              transition={{delay: i * 0.5, duration: 0.3}}>
              <Badge
                variant='secondary'
                className='font-normal transition-colors duration-300 hover:bg-primary hover:text-white'>
                {skill}
              </Badge>
            </motion.div>
          ))}
        </div>
      </div>

      <motion.div
        className='absolute bottom-0 left-0 h-1 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500'
        initial={{width: "0%"}}
        animate={{width: "100%"}}
        transition={{duration: 3, delay: 0.3}}
      />
    </motion.div>
  );
};

/**
 * @description Component that displays a timeline of professional experiences.
 * This component renders an interactive timeline of work experiences, with a navigation
 * panel on the left side and detailed information about the selected experience on the right.
 *
 * It uses framer-motion for animations and next-intl for translations.
 *
 * The component fetches experience data from translation files and displays them in a
 * responsive layout. Users can click on different experiences in the timeline to view
 * detailed information about each role, including responsibilities, achievements, and skills.
 * @returns A section element containing the experience timeline and detailed work card
 */
export default function Experience() {
  const t = useTranslations("About.Author.Experiences");
  const [activeExpIndex, setActiveExpIndex] = useState<number>(0);
  const experiences = [
    {
      company: t("microsoft3.company"),
      role: t("microsoft3.title"),
      period: t("microsoft3.period"),
      location: t("microsoft3.location"),
      description: t("microsoft3.description"),
      responsibilities: t("microsoft3.responsibilites")
        .split("#")
        .filter((item) => item.trim().length > 3),
      achievements: t("microsoft3.achievements")
        .split("#")
        .filter((item) => item.trim().length > 3),
      skills: t("microsoft3.techAndSkills")
        .split("#")
        .filter((item) => item.trim().length > 0),
      logo: <CgMicrosoft className='h-10 w-10 text-muted-foreground' />,
    },
    {
      company: t("microsoft2.company"),
      role: t("microsoft2.title"),
      period: t("microsoft2.period"),
      location: t("microsoft2.location"),
      description: t("microsoft2.description"),
      responsibilities: t("microsoft2.responsibilites")
        .split("#")
        .filter((item) => item.trim().length > 3),
      achievements: t("microsoft2.achievements")
        .split("#")
        .filter((item) => item.trim().length > 3),
      skills: t("microsoft2.techAndSkills")
        .split("#")
        .filter((item) => item.trim().length > 0),
      logo: <CgMicrosoft className='h-10 w-10 text-muted-foreground' />,
    },
    {
      company: t("microsoft1.company"),
      role: t("microsoft1.title"),
      period: t("microsoft1.period"),
      location: t("microsoft1.location"),
      description: t("microsoft1.description"),
      responsibilities: t("microsoft1.responsibilites")
        .split("#")
        .filter((item) => item.trim().length > 3),
      achievements: t("microsoft1.achievements")
        .split("#")
        .filter((item) => item.trim().length > 3),
      skills: t("microsoft1.techAndSkills")
        .split("#")
        .filter((item) => item.trim().length > 0),
      logo: <CgMicrosoft className='h-10 w-10 text-muted-foreground' />,
    },
    {
      company: t("intel.company"),
      role: t("intel.title"),
      period: t("intel.period"),
      location: t("intel.location"),
      description: t("intel.description"),
      responsibilities: t("intel.responsibilites")
        .split("#")
        .filter((item) => item.trim().length > 3),
      achievements: t("intel.achievements")
        .split("#")
        .filter((item) => item.trim().length > 3),
      skills: t("intel.techAndSkills")
        .split("#")
        .filter((item) => item.trim().length > 0),
      logo: <SiIntel className='h-10 w-10 text-muted-foreground' />,
    },
    {
      company: t("ubisoft.company"),
      role: t("ubisoft.title"),
      period: t("ubisoft.period"),
      location: t("ubisoft.location"),
      description: t("ubisoft.description"),
      responsibilities: t("ubisoft.responsibilites")
        .split("#")
        .filter((item) => item.trim().length > 3),
      achievements: t("ubisoft.achievements")
        .split("#")
        .filter((item) => item.trim().length > 3),
      skills: t("ubisoft.techAndSkills")
        .split("#")
        .filter((item) => item.trim().length > 0),
      logo: <SiUbisoft className='h-10 w-10 text-muted-foreground' />,
    },
  ] satisfies ExperienceType[];

  const currentExperience = experiences.at(activeExpIndex)!;

  return (
    <section className='bg-muted/30 px-4 py-20 md:px-8'>
      <div className='mx-auto max-w-6xl'>
        <motion.div
          initial={{opacity: 0, y: 20}}
          animate={{opacity: 1, y: 0}}
          transition={{duration: 0.6}}
          className='mb-16 text-center'>
          <h2 className='blue-underline relative mb-4 inline-block text-3xl font-bold md:text-4xl'>{t("title")}</h2>
          <p className='mx-auto max-w-2xl text-muted-foreground'>{t("subtitle")}</p>
        </motion.div>

        <div className='grid gap-8 md:grid-cols-[1fr_2fr]'>
          {/* Timeline Navigation */}
          <div className='relative'>
            <div className='absolute bottom-0 left-8 top-0 w-px bg-border/50' />

            {experiences.map((exp, index) => (
              <motion.div
                key={`${exp.company}-${exp.period}`}
                className='relative mb-8 last:mb-0'
                initial={{opacity: 0, x: -20}}
                animate={{opacity: 1, x: 0}}
                transition={{delay: index * 0.1, duration: 0.5}}>
                <button
                  type='button'
                  onClick={() => setActiveExpIndex(index)}
                  className={`relative flex items-start pl-16 ${activeExpIndex === index ? "opacity-100" : "opacity-70 hover:opacity-100"} transition-opacity duration-300`}>
                  <div
                    className={`absolute left-0 z-10 flex h-16 w-16 items-center justify-center rounded-full transition-all duration-300 ${activeExpIndex === index ? "bg-primary/20" : "bg-muted"}`}>
                    <div
                      className={`flex h-10 w-10 items-center justify-center rounded-full ${activeExpIndex === index ? "bg-primary text-white" : "bg-background text-muted-foreground"}`}>
                      <TbBriefcase className='h-5 w-5' />
                    </div>
                  </div>

                  <div className='text-left'>
                    <h3 className={`text-xl font-bold transition-colors duration-300 ${activeExpIndex === index ? "text-glow" : ""}`}>
                      {exp.company}
                    </h3>
                    <p className='text-muted-foreground'>{exp.role}</p>
                    <div className='mt-1 flex items-center text-sm text-muted-foreground'>
                      <TbCalendar className='mr-1 h-3 w-3' />
                      <span>{exp.period}</span>
                    </div>
                  </div>
                </button>
              </motion.div>
            ))}
          </div>

          {/* Timeline Content */}
          <div className='relative h-full'>
            <AnimatePresence mode='wait'>
              <WorkCard experience={currentExperience} />
            </AnimatePresence>
          </div>
        </div>
      </div>
    </section>
  );
}
