// sites/arolariu.ro/src/app/about/_components/Hero.tsx
"use client";

import {Badge, Button} from "@arolariu/components";
import {motion} from "motion/react";
import {useTranslations} from "next-intl";
import Link from "next/link";
import {TbChevronDown, TbRocket, TbSparkles} from "react-icons/tb";

/**
 * Hero section for the About hub page.
 * Features animated background, gradient text, and CTAs.
 */
export default function Hero(): React.JSX.Element {
  const t = useTranslations("About.Hub.hero");

  return (
    <section className='relative flex min-h-[80vh] w-full flex-col items-center justify-center overflow-hidden px-4 py-20'>
      {/* Animated background orbs */}
      <div className='pointer-events-none absolute inset-0 overflow-hidden'>
        <motion.div
          className='absolute -top-40 -left-40 h-80 w-80 rounded-full bg-gradient-to-br from-blue-500/20 to-cyan-500/20 blur-3xl'
          animate={{
            x: [0, 50, 0],
            y: [0, 30, 0],
            scale: [1, 1.1, 1],
          }}
          transition={{
            duration: 8,
            repeat: Infinity,
            ease: "easeInOut",
          }}
        />
        <motion.div
          className='absolute -right-40 -bottom-40 h-96 w-96 rounded-full bg-gradient-to-br from-purple-500/20 to-pink-500/20 blur-3xl'
          animate={{
            x: [0, -40, 0],
            y: [0, -30, 0],
            scale: [1, 1.15, 1],
          }}
          transition={{
            duration: 10,
            repeat: Infinity,
            ease: "easeInOut",
          }}
        />
        <motion.div
          className='absolute top-1/2 left-1/2 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full bg-gradient-to-br from-indigo-500/10 to-blue-500/10 blur-3xl'
          animate={{
            scale: [1, 1.2, 1],
            opacity: [0.3, 0.6, 0.3],
          }}
          transition={{
            duration: 6,
            repeat: Infinity,
            ease: "easeInOut",
          }}
        />
      </div>

      {/* Grid pattern overlay */}
      <div
        className='pointer-events-none absolute inset-0 bg-[linear-gradient(rgba(100,100,100,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(100,100,100,0.03)_1px,transparent_1px)] bg-[size:50px_50px]'
        aria-hidden='true'
      />

      {/* Content */}
      <motion.div
        className='relative z-10 flex max-w-4xl flex-col items-center text-center'
        initial={{opacity: 0, y: 20}}
        animate={{opacity: 1, y: 0}}
        transition={{duration: 0.6}}>
        {/* Badge */}
        <motion.div
          initial={{opacity: 0, scale: 0.9}}
          animate={{opacity: 1, scale: 1}}
          transition={{delay: 0.2}}>
          <Badge
            variant='secondary'
            className='mb-6 px-4 py-1.5 text-sm font-medium'>
            <TbSparkles className='mr-2 h-4 w-4' />
            {t("badge")}
          </Badge>
        </motion.div>

        {/* Main title */}
        <motion.h1
          className='from-gradient-from via-gradient-via to-gradient-to mb-6 bg-gradient-to-r bg-clip-text text-5xl font-bold tracking-tight text-transparent sm:text-6xl lg:text-7xl'
          initial={{opacity: 0, y: 20}}
          animate={{opacity: 1, y: 0}}
          transition={{delay: 0.3}}>
          {t("title")}
        </motion.h1>

        {/* Subtitle */}
        <motion.p
          className='text-muted-foreground mb-10 max-w-2xl text-lg leading-relaxed sm:text-xl'
          initial={{opacity: 0, y: 20}}
          animate={{opacity: 1, y: 0}}
          transition={{delay: 0.4}}>
          {t("subtitle")}
        </motion.p>

        {/* CTA buttons */}
        <motion.div
          className='flex flex-col gap-4 sm:flex-row'
          initial={{opacity: 0, y: 20}}
          animate={{opacity: 1, y: 0}}
          transition={{delay: 0.5}}>
          <Button
            asChild
            size='lg'
            className='group px-8'>
            <Link href='/about/the-platform'>
              <TbRocket className='mr-2 h-5 w-5 transition-transform group-hover:-translate-y-0.5' />
              {t("ctaPrimary")}
            </Link>
          </Button>
          <Button
            asChild
            variant='outline'
            size='lg'
            className='px-8'>
            <Link href='/about/the-author'>{t("ctaSecondary")}</Link>
          </Button>
        </motion.div>
      </motion.div>

      {/* Scroll indicator */}
      <motion.div
        className='absolute bottom-8 left-1/2 -translate-x-1/2'
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{delay: 1}}>
        <motion.div
          animate={{y: [0, 8, 0]}}
          transition={{duration: 2, repeat: Infinity, ease: "easeInOut"}}>
          <TbChevronDown className='text-muted-foreground h-6 w-6' />
        </motion.div>
      </motion.div>
    </section>
  );
}

// sites/cv.arolariu.ro/src/presentation/human/Hero.svelte
<script lang="ts">
  import {author} from "@/data";

  let heroVisible = $state(false);
  let imageLoaded = $state(false);

  // Trigger hero animation shortly after mount
  $effect(() => {
    const t = setTimeout(() => (heroVisible = true), 200);
    return () => clearTimeout(t);
  });

  function handleImageLoad() {
    imageLoaded = true;
  }
</script>

<section
  class="pt-24 pb-16 px-6 relative overflow-hidden"
  style="view-transition-name: hero-section;">
  <!-- Theme-aware animated gradient background elements -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <div
      class="absolute top-20 left-10 w-72 h-72 rounded-full blur-3xl animate-float transition-all duration-500 bg-gradient-to-tr from-blue-500/10 via-purple-500/8 to-pink-500/5 dark:from-blue-500/15 dark:via-purple-500/10 dark:to-pink-500/5">
    </div>
    <div
      class="absolute bottom-20 right-10 w-96 h-96 rounded-full blur-3xl animate-float-delayed transition-all duration-500 bg-gradient-to-tr from-pink-500/10 via-purple-500/8 to-blue-500/5 dark:from-pink-500/15 dark:via-purple-500/10 dark:to-blue-500/5">
    </div>
  </div>

  <div class="container mx-auto text-center relative z-10">
    <!-- Profile Image with enhanced animation -->
    <div class="mb-8 relative inline-block">
      <div
        class="absolute inset-0 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500 blur-md opacity-50 scale-105 transition-opacity duration-500"
        class:opacity-0={!imageLoaded}>
      </div>
      <img
        src="/author.jpeg"
        alt={author.name}
        onload={handleImageLoad}
        class="w-48 h-48 rounded-full mx-auto border-4 border-blue-500 dark:border-blue-400 shadow-xl relative transition-all duration-700 ease-out"
        class:opacity-100={heroVisible && imageLoaded}
        class:opacity-0={!heroVisible || !imageLoaded}
        class:scale-100={heroVisible}
        class:scale-90={!heroVisible}
        style="view-transition-name: profile-image;" />
    </div>

    <!-- Name with staggered letter reveal feel -->
    <div
      class="transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 100ms;">
      <h1 class="text-4xl md:text-6xl font-bold mb-4">
        <span class="inline-block">Alexandru-Razvan</span>
        <span class="text-blue-600 dark:text-blue-400 inline-block"> Olariu </span>
      </h1>
    </div>

    <!-- Tagline with animated underline effect -->
    <div
      class="transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 250ms;">
      <p class="text-xl md:text-2xl text-gray-600 dark:text-gray-300 mb-6 relative inline-block">
        <span class="relative">
          Software Engineer
          <span
            class="absolute bottom-0 left-0 w-full h-0.5 bg-blue-500/30 dark:bg-blue-400/30 transform origin-left transition-transform duration-700 delay-700"
            class:scale-x-100={heroVisible}
            class:scale-x-0={!heroVisible}></span>
        </span>
        <span class="text-gray-400 dark:text-gray-500 mx-2">|</span>
        <span class="relative">
          Solution Architect
          <span
            class="absolute bottom-0 left-0 w-full h-0.5 bg-purple-500/30 dark:bg-purple-400/30 transform origin-left transition-transform duration-700 delay-800"
            class:scale-x-100={heroVisible}
            class:scale-x-0={!heroVisible}></span>
        </span>
        <span class="text-gray-400 dark:text-gray-500 mx-2">|</span>
        <span class="relative">
          Mentor
          <span
            class="absolute bottom-0 left-0 w-full h-0.5 bg-pink-500/30 dark:bg-pink-400/30 transform origin-left transition-transform duration-700 delay-900"
            class:scale-x-100={heroVisible}
            class:scale-x-0={!heroVisible}></span>
        </span>
      </p>
    </div>

    <!-- Description -->
    <div
      class="transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 400ms;">
      <p class="text-lg text-gray-500 dark:text-gray-400 mb-8 max-w-2xl mx-auto leading-relaxed">
        {new Date().getFullYear() - 2000}-year-old passionate software engineer based in {author.location}, dedicated to creating innovative
        solutions and building exceptional digital experiences.
      </p>
    </div>

    <!-- CTA Buttons -->
    <div
      class="flex flex-col sm:flex-row gap-4 justify-center transition-all duration-700 ease-out"
      class:opacity-100={heroVisible}
      class:opacity-0={!heroVisible}
      class:translate-y-0={heroVisible}
      class:translate-y-6={!heroVisible}
      style="transition-delay: 550ms;">
      <a
        href="#contact"
        class="group bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 text-white px-8 py-3 rounded-xl font-semibold transition-all duration-300 hover:shadow-lg hover:shadow-blue-500/25 dark:hover:shadow-blue-400/25 hover:-translate-y-0.5 active:translate-y-0">
        <span class="flex items-center justify-center gap-2">
          Get In Touch
          <svg
            class="w-4 h-4 transition-transform group-hover:translate-x-1"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M17 8l4 4m0 0l-4 4m4-4H3" />
          </svg>
        </span>
      </a>
      <a
        href="#experience"
        class="group border-2 border-blue-500 text-blue-600 dark:text-blue-400 hover:bg-blue-500 hover:text-white dark:hover:bg-blue-400 dark:hover:text-gray-900 px-8 py-3 rounded-xl font-semibold transition-all duration-300 hover:-translate-y-0.5 active:translate-y-0">
        <span class="flex items-center justify-center gap-2">
          View My Work
          <svg
            class="w-4 h-4 transition-transform group-hover:translate-y-0.5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M19 14l-7 7m0 0l-7-7m7 7V3" />
          </svg>
        </span>
      </a>
    </div>
  </div>
</section>

<style>
  @keyframes float {
    0%,
    100% {
      transform: translateY(0) scale(1);
    }
    50% {
      transform: translateY(-20px) scale(1.05);
    }
  }

  .animate-float {
    animation: float 8s ease-in-out infinite;
  }

  .animate-float-delayed {
    animation: float 8s ease-in-out infinite;
    animation-delay: -4s;
  }

  @media (prefers-reduced-motion: reduce) {
    .animate-float,
    .animate-float-delayed {
      animation: none;
    }
  }
</style>
