// sites/arolariu.ro/src/app/_components/Testimonials.tsx
"use client";

import {Avatar, AvatarFallback} from "@arolariu/components/avatar";
import {Card, CardContent} from "@arolariu/components/card";
import {motion, useInView} from "motion/react";
import {useTranslations} from "next-intl";
import {useRef} from "react";
import {TbQuote} from "react-icons/tb";

const testimonials = ["t1", "t2", "t3"] as const;

/**
 * Testimonials section displaying social proof from colleagues.
 */
export default function Testimonials(): React.JSX.Element {
  const t = useTranslations("Home.testimonials");
  const ref = useRef<HTMLElement>(null);
  const isInView = useInView(ref, {once: true, margin: "-100px"});

  return (
    <section
      ref={ref}
      className='relative w-full bg-gradient-to-b from-transparent via-purple-500/5 to-transparent px-4 py-20'>
      <div className='mx-auto max-w-6xl'>
        {/* Section header */}
        <motion.div
          className='mb-16 text-center'
          initial={{opacity: 0, y: 20}}
          animate={isInView ? {opacity: 1, y: 0} : {}}
          transition={{duration: 0.6}}>
          <h2 className='mb-4 text-3xl font-bold sm:text-4xl'>
            <span className='bg-gradient-to-r from-cyan-500 to-purple-500 bg-clip-text text-transparent'>{t("title")}</span>
          </h2>
          <p className='text-muted-foreground mx-auto max-w-2xl text-lg'>{t("subtitle")}</p>
        </motion.div>

        {/* Testimonials grid */}
        <div className='grid gap-8 md:grid-cols-3'>
          {testimonials.map((key, index) => (
            <motion.div
              key={key}
              initial={{opacity: 0, y: 30}}
              animate={isInView ? {opacity: 1, y: 0} : {}}
              transition={{delay: 0.2 + index * 0.15, duration: 0.5}}>
              <Card className='group hover:border-primary/30 relative h-full transition-all duration-300 hover:-translate-y-1 hover:shadow-lg'>
                {/* Quote icon */}
                <div className='bg-primary absolute -top-4 -left-2 rounded-full p-2'>
                  <TbQuote className='h-5 w-5 text-white' />
                </div>

                <CardContent className='p-6 pt-8'>
                  {/* Quote */}
                  <p className='text-muted-foreground mb-6 text-sm italic leading-relaxed'>"{t(`items.${key}.quote`)}"</p>

                  {/* Author */}
                  <div className='flex items-center gap-3'>
                    <Avatar className='h-10 w-10'>
                      <AvatarFallback className='bg-gradient-to-br from-cyan-500 to-purple-500 text-xs text-white'>
                        {t(`items.${key}.author`)
                          .split(" ")
                          .map((n) => n.charAt(0))
                          .join("")}
                      </AvatarFallback>
                    </Avatar>
                    <div>
                      <p className='text-sm font-semibold'>{t(`items.${key}.author`)}</p>
                      <p className='text-muted-foreground text-xs'>{t(`items.${key}.role`)}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

// sites/cv.arolariu.ro/src/presentation/human/Testimonials.svelte
<script lang="ts">
  import {AnimatedSection} from "@/components/motion";
  import {testimonialsAsArray} from "@/data/testimonials";
</script>

<section
  id="testimonials"
  class="py-16 px-6">
  <div class="container mx-auto">
    <AnimatedSection
      id="testimonials-title"
      animation="fade-up">
      <div class="mb-12 text-center">
        <h2
          id="testimonials-heading"
          class="font-bold text-3xl">
          What <span class="text-blue-600 dark:text-blue-400">Colleagues Say</span>
        </h2>
        <p class="mt-3 text-gray-600 dark:text-gray-400 max-w-3xl mx-auto text-sm">
          Authentic testimonials from Microsoft colleagues who have worked alongside Alexandru.
        </p>
      </div>
    </AnimatedSection>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      {#each testimonialsAsArray as testimonial, index}
        <AnimatedSection
          animation="fade-up"
          delay={100 * index}>
          <div
            class="relative bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm rounded-2xl p-6 md:p-8 shadow-xl border border-gray-200/50 dark:border-gray-700/50 h-full flex flex-col">
            <!-- Quote Icon -->
            <div class="flex justify-center mb-4">
              <svg
                class="w-8 h-8 text-blue-500 dark:text-blue-400 opacity-50"
                fill="currentColor"
                viewBox="0 0 24 24">
                <path
                  d="M14.017 21v-7.391c0-5.704 3.731-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 9-10.609l.996 2.151c-2.433.917-3.996 3.638-3.996 5.849h4v10h-10z" />
              </svg>
            </div>

            <!-- Testimonial Content -->
            <div class="text-center flex-grow flex flex-col justify-center">
              <blockquote class="text-base text-gray-700 dark:text-gray-300 leading-relaxed mb-6 italic">
                "{testimonial.quote}"
              </blockquote>
            </div>

            <div class="flex flex-col items-center mt-auto pt-6">
              <div
                class="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center mb-3 hover-scale">
                <span class="text-white font-bold text-lg">
                  {testimonial.author.charAt(0)}
                </span>
              </div>
              <h4 class="font-semibold text-gray-900 dark:text-white text-base">
                {testimonial.author}
              </h4>
              <p class="text-blue-600 dark:text-blue-400 font-medium text-sm">
                {testimonial.position}
              </p>
              <p class="text-gray-600 dark:text-gray-400 text-xs">
                {testimonial.company}
              </p>
            </div>
          </div>
        </AnimatedSection>
      {/each}
    </div>
  </div>
</section>
